export enum ECsGoRarity {
  CONSUMER_GRADE = 'Consumer Grade',
  MIL_SPEC_GRADE = 'Mil-Spec Grade',
  INDUSTRIAL_GRADE = 'Industrial Grade',
  RESTRICTED = 'Restricted',
  CLASSIFIED = 'Classified',
  COVERT = 'Covert',
  EXCEPTIONAL = 'Exceptional',
  SUPERIOR = 'Superior',
  DISTINGUISHED = 'Distinguished',
  MASTER = 'Master',
  BASE_GRADE = 'Base Grade',
  EXTRAORDINARY = 'Extraordinary',
  HIGH_GRADE = 'High Grade',
  REMARKABLE = 'Remarkable',
  EXOTIC = 'Exotic',
  CONTRABAND = 'Contraband',
}

export enum ECsGoRarityColor {
  CONSUMER_GRADE = '#afafaf',
  MIL_SPEC_GRADE = '#1155dd',
  INDUSTRIAL_GRADE = '#87c7ff',
  RESTRICTED = '#8847ff',
  CLASSIFIED = '#d32ce6',
  COVERT = '#eb4b4b',
  EXCEPTIONAL = '#8847ff',
  SUPERIOR = '#d32ce6',
  DISTINGUISHED = '#1155dd',
  MASTER = '#eb4b4b',
  BASE_GRADE = '#afafaf',
  EXTRAORDINARY = '#eb4b4b',
  HIGH_GRADE = '#1155dd',
  REMARKABLE = '#8847ff',
  EXOTIC = '#d32ce6',
  CONTRABAND = '#f2bc4b',
}
