export enum ECsGoType {
  PISTOL = 'Pistol',
  SMG = 'SMG',
  RIFLE = 'Rifle',
  SNIPER_RIFLE = 'Sniper Rifle',
  SHOTGUN = 'Shotgun',
  MACHINEGUN = 'Machinegun',
  AGENT = 'Agent',
  KNIFE = 'Knife',
  CONTAINER = 'Container',
  STICKER = 'Sticker',
  GRAFFITI = 'Graffiti',
  GLOVES = 'Gloves',
  MUSIC_KIT = 'Music Kit',
  PATCH = 'Patch',
  COLLECTIBLE = 'Collectible',
  KEY = 'Key',
  PASS = 'Pass',
  GIFT = 'Gift',
  TAG = 'Tag',
  TOOL = 'Tool',
}
